### ISSUE TITLE
Make a ui/ux design for projects

### ISSUE THREAD

**Issue by OluwakejiOnabajo** [InventorsDev/sdg-004#2]
Prepare the ui/ux design for the user interface so the frontend task can begin as soon as possible

**Comment by OluwakejiOnabajo** [comment]
This is the design for the landing page work can now begin on it. Other ui/ux design coming
![speakup](https://user-images.githubusercontent.com/62175369/113474124-d5880100-9465-11eb-874d-215cffe1f5c4.jpg)

**Comment by samstick1** [comment]
![Mobile index page](https://user-images.githubusercontent.com/81930575/113787092-f1bbc480-9729-11eb-9001-03b5ac06e60e.jpg)
![Desktop index page](https://user-images.githubusercontent.com/81930575/113787161-08621b80-972a-11eb-9491-476c9aaddd67.jpg)
![Signup page 1](https://user-images.githubusercontent.com/81930575/113787199-17e16480-972a-11eb-81cd-a0afe7eca0e9.jpg)
![Signup page](https://user-images.githubusercontent.com/81930575/113787211-1f087280-972a-11eb-8eaa-afe4c8dd004e.jpg)
![Signup page 1](https://user-images.githubusercontent.com/81930575/113787282-419a8b80-972a-11eb-8d5c-c330629ad9a2.jpg)
![Signup page 2](https://user-images.githubusercontent.com/81930575/113787313-51b26b00-972a-11eb-9f5e-f38cbba1df96.jpg)
![Signup page 3](https://user-images.githubusercontent.com/81930575/113787324-57a84c00-972a-11eb-90f5-ed4ad0aee573.jpg)
![login page](https://user-images.githubusercontent.com/81930575/113787347-60991d80-972a-11eb-8049-b881a689feb4.jpg)
![Tips and guides](https://user-images.githubusercontent.com/81930575/113787388-74448400-972a-11eb-9f0b-1164b21b87f3.jpg)
![Tips and guides view](https://user-images.githubusercontent.com/81930575/113787397-77d80b00-972a-11eb-917c-3f02161c9ef1.jpg)
![Responder dashboard](https://user-images.githubusercontent.com/81930575/113787419-81fa0980-972a-11eb-95b7-9b1d32df6e9d.jpg)
![Reporter dashboard](https://user-images.githubusercontent.com/81930575/113787433-8aeadb00-972a-11eb-8c85-10ea419627a1.jpg)
Ui/ux completed.
