### ISSUE TITLE
Make a UI UX Design for the chatbot

### ISSUE THREAD

**Issue by OluwakejiOnabajo** [InventorsDev/sdg-004#7]
Make a UI UX Design for the user chatbot

**Comment by samstick1** [comment]
This is UI UX Design for the chatbot. Let's code
![chatbot](https://user-images.githubusercontent.com/81930575/114394778-7deb4300-9b93-11eb-9ac7-432c364ad8ae.png)

**Comment by OluwakejiOnabajo** [comment]
Implementation of chatbot in progress
